### PR TITLE
Fix number comparison

### LINKED ISSUE #371: expect(elem).toBeElementsArrayOfSize gte behaves as strict equals instead of greater than or equal
```
   expect(sessionCountListBeforeCleanUp).toBeElementsArrayOfSize({ gte: 3 })
```

The above line, when checking that the array is greater or equal than 3, fails if it gets a number greater than 3.  In this example, our `sessionCountListBeforeCleanUp` variable is of size 4.

The below output seems to contradict itself, since a value of 4 is indeed greater than or equal to 4.  

```
Expect $$(`//div[@class="span6 class-timings-list"]/ul/li[@class="hasHoverStyles"]`) to be elements array of size

Expected: ">= 3"
Received: 4
[chrome 83.0.4103.61 linux #0-0] Error: Expect $$(`//div[@class="span6 class-timings-list"]/ul/li[@class="hasHoverStyles"]`) to be elements array of size
[chrome 83.0.4103.61 linux #0-0]
[chrome 83.0.4103.61 linux #0-0] Expected: ">= 3"
[chrome 83.0.4103.61 linux #0-0] Received: 4
[chrome 83.0.4103.61 linux #0-0]     at Context.<anonymous>
```

While we would love to have a strict equals version of this, the gte behavior does not seem correct.

Platform: Mac OS
WebdriverIO:  v7.0.7

### PR DESCRIPTION
**Pull request by TuxedoFish**
fixes #371 

To fix the number comparison errors:

- writes tests for compareNumbers in utils.test (failing)
- updates compareNumbers in utils
- updates numberError in formatMessage
- updates toBeElementsArrayOfSize / toHaveChildren / toBeRequestedTimes that use these functions

~~Upon fixing this, I discovered that there was a test that was failing now that involved isNot and upon closer inspection I discovered that there was issues with waitUntil usage of isNot so I updated this.~~

- ~~writes tests for waitUntil in utils.test (failing)~~
- ~~updates waitUntil to pass these test conditions~~
- ~~updates all test cases that use isNot that have incorrect behaviour~~

### CODE REVIEW

File: src/matchers/element/toHaveChildren.ts [hunk 1]
```diff
@@ -1,45 +1,51 @@
...
 import { runExpect } from '../../util/expectAdapter'
 
-async function condition(el: WebdriverIO.Element, gte: number, lte: number, eq?: number): Promise<any> {
+async function condition(el: WebdriverIO.Element, options: ExpectWebdriverIO.NumberOptions): Promise<any> {
     const children = await el.$$('./*')
+
+    // If no options passed in + children exists
+    if(!options.lte && !options.gte && !options.eq) {
+        return {
+            result: (typeof children == 'undefined' || !children) ? false : true,
```
Comment (mgrybyk) [inline src/matchers/element/toHaveChildren.ts:10]: Can you please simplify the condition?
```suggestion
            result: children != null,
```

**Review by mgrybyk — CHANGES_REQUESTED** [review]

File: src/matchers/element/toHaveChildren.ts (hunk 1 above)
Comment (TuxedoFish) [reply src/matchers/element/toHaveChildren.ts:10]: Yes nice, that is much nicer. I am going to see if I can write a unit test for this case as well tonight 👍  I'll push the change first though

Also do you think it is worth doing `children?.length` in case its null?

Comment (mgrybyk) [reply src/matchers/element/toHaveChildren.ts:10]: Sounds good, can you please double check it?

Comment (TuxedoFish) [reply src/matchers/element/toHaveChildren.ts]: Added a test case for this and the optional chaining was needed so added it in. Also I noticed I had removed the 3rd param from the 3 matchers and so I added this back in because otherwise this kind of expect:

```
expect(el).toHaveChildren(5, {wait:5000})
```

Would have been broken so I added it back in! My bad

Was there anything else you want me to change?

File: test/matchers/mock/toBeRequestedTimes.test.ts [hunk 2]
```diff
@@ -83,21 +83,21 @@ describe('toBeRequestedTimes', () => {
...
 
         // expect(mock).not.toBeRequestedTimes(0) should pass
         const result3 = await toBeRequestedTimes.call({ isNot: true }, mock, 0)
-        expect(result3.pass).toBe(false)
+        expect(result3.pass).toBe(true)
 
         // expect(mock).not.toBeRequestedTimes(1) should fail
         const result4 = await toBeRequestedTimes.call({ isNot: true }, mock, 1)
-        expect(result4.pass).toBe(true)
+        expect(result4.pass).toBe(false)
```
Comment (christian-bromann) [inline test/matchers/mock/toBeRequestedTimes.test.ts:100]: Why are all these test results reversed? The matcher doesn't seem to be related with your change.

File: test/matchers/mock/toBeRequested.test.ts [hunk 3]
```diff
@@ -51,13 +51,13 @@ describe('toBeRequested', () => {
...
         const result = await toBeRequested.call({ isNot: true }, mock)
-        expect(result.pass).toBe(false)
+        expect(result.pass).toBe(true)
 
         mock.calls.push(mockMatch)
 
         // expect(mock).not.toBeRequested() should fail
         const result4 = await toBeRequested.call({ isNot: true }, mock)
-        expect(result4.pass).toBe(true)
+        expect(result4.pass).toBe(false)
```
Comment (christian-bromann) [inline test/matchers/mock/toBeRequested.test.ts:60]: same

File: src/utils.ts [hunk 4]
```diff
@@ -30,7 +30,7 @@ const waitUntil = async (condition: () => Promise<boolean>, isNot = false, {
         await browser.waitUntil(async () => {
             error = undefined
             try {
-                return isNot !== await condition()
+                return isNot ? !(await condition()) : await condition()
```
Comment (christian-bromann) [inline src/utils.ts:33]:
```suggestion
                const result = await condition()
                return isNot ? !result : result
```

File: src/utils.ts [hunk 5]
```diff
@@ -21,7 +21,7 @@ const waitUntil = async (condition: () => Promise<boolean>, isNot = false, {
 ): Promise<boolean> => {
     // single attempt
     if (wait === 0) {
-        return await condition()
+        return isNot ? !(await condition()) : await condition()
```
Comment (christian-bromann) [inline src/utils.ts:24]:
```suggestion
        const result = await condition()
        return isNot ? !result : result
```

File: src/utils.ts [hunk 6]
```diff
@@ -44,9 +44,11 @@ const waitUntil = async (condition: () => Promise<boolean>, isNot = false, {
             throw error
         }
 
-        return !isNot
+        // condition was fufilled after wait
+        return true
     } catch (err) {
-        return isNot
+        // condition was not fufilled after wait
+        return false
```
Comment (christian-bromann) [inline src/utils.ts:51]: I believe this is causing the mock matcher tests to fail. I would recommend to keep as is.

**Review by christian-bromann — COMMENTED** [review]
Some comments.

@mgrybyk can you take another look?

File: test/utils.test.ts [hunk 7]
```diff
@@ -1,50 +1,155 @@
...
+                const pass = await waitUntil(condition, true, {wait: 0})
+                expect(pass).toBe(true)
+            })
+
+            test('should fail if isNot is false and wait is 0', async () => {
+                const pass = await waitUntil(condition, false, {wait: 0})
+                expect(pass).toBe(false)
+            })
+        })
+    })
```
Comment (TuxedoFish) [inline test/utils.test.ts:112]: @christian-bromann The reason I changed the waitUntil function was because I initially wrote these test cases and some of them failed. Are these test cases the correct interpretation of isNot? Because maybe I have confused something here. 

Then having updated the waitUntil to follow this logical pattern I then noticed that some of the tests using isNot didn't seem to align with this logic and so I changed these conditions as I believed they were the wrong way around. The comments above assertions also seemed to point to this

File: test/matchers/mock/toBeRequestedTimes.test.ts (hunk 2 above)
Comment (TuxedoFish) [reply test/matchers/mock/toBeRequestedTimes.test.ts:100]: Following on from my comment below about why I changed waitUntil, I then looked at some of the old tests for isNot and they seemed to be the wrong way around and the comment here seems to agree.

Taking line 94 for example:

`expect(mock).not.toBeRequestedTimes(0) should pass`

Because we have online 92 pushed mockMatch then we expect in the positive case toBeRequestedTimes(1) would pass.

Furthermore .toBeRequestedTimes(0) is false and finally .not.toBeRequestedTimes(0) is true? Again happy to be wrong on this but it seems to me that it was the wrong way around prior to the update to waitUntil

**Comment by christian-bromann** [comment]
@TuxedoFish anything I can do to move this forward?

**Comment by TuxedoFish** [comment]
@christian-bromann I can go through this PR and ensure there are no changes to the waitUntil, I think maybe I could open an issue for that for discussion because it slightly confused me at the time but I shouldn't have intertwined it with this PR!

I'll get cracking on fixing this PR this week though

File: src/utils.ts (hunk 6 above)
Comment (TuxedoFish) [reply src/utils.ts]: I have removed this change and the tests now

**Comment by TuxedoFish** [comment]
@christian-bromann Should be okay to review now, thanks for the patience!

File: src/matchers/element/toHaveChildren.ts [hunk 8]
```diff
@@ -1,45 +1,51 @@
...
 import { runExpect } from '../../util/expectAdapter'
 
-async function condition(el: WebdriverIO.Element, gte: number, lte: number, eq?: number): Promise<any> {
+async function condition(el: WebdriverIO.Element, options: ExpectWebdriverIO.NumberOptions): Promise<any> {
     const children = await el.$$('./*')
+
+    // If no options passed in + children exists
+    if(!options.lte && !options.gte && !options.eq) {
+        return {
+            result: children != null,
```
Comment (christian-bromann) [inline src/matchers/element/toHaveChildren.ts:10]: `children` will never be undefined or be anything different than an array. So I suggest it should be the following:
```suggestion
            result: children.length > 0, 
```
Correct?

File: src/utils.ts [hunk 9]
```diff
@@ -80,16 +80,28 @@ async function executeCommandBe(
     }
 }
 
-const compareNumbers = (actual: number, gte: number, lte: number, eq?: number): boolean => {
-    if (typeof eq === 'number') {
-        return actual === eq
+const compareNumbers = (actual: number, options: ExpectWebdriverIO.NumberOptions = {}): boolean => {
+    // Equals case
+    if (typeof options.eq == 'number') {
+        return actual == options.eq
```
Comment (christian-bromann) [inline src/utils.ts:86]: Let's try to parse the `actual` value to an integer and throw if this fails.

```suggestion
        return actual === options.eq
```

File: src/utils.ts [hunk 10]
```diff
@@ -80,16 +80,28 @@ async function executeCommandBe(
...
     }
 
-    if (lte > 0 && actual > lte) {
-        return false
+    // Greater than or equal AND less than or equal case
+    if (typeof options.gte == 'number' && typeof options.lte == 'number') {
```
Comment (christian-bromann) [inline src/utils.ts:90]:
```suggestion
    if (typeof options.gte === 'number' && typeof options.lte === 'number') {
```

File: src/utils.ts [hunk 11]
```diff
@@ -80,16 +80,28 @@ async function executeCommandBe(
...
+        return actual >= options.gte && actual <= options.lte
     }
 
-    return actual >= gte
+    // Greater than or equal case
+    if (typeof options.gte == 'number') {
```
Comment (christian-bromann) [inline src/utils.ts:95]:
```suggestion
    if (typeof options.gte === 'number') {
```

File: src/utils.ts [hunk 12]
```diff
@@ -80,16 +80,28 @@ async function executeCommandBe(
...
+        return actual >= options.gte
+    }
+
+    // Less than or equal case
+    if (typeof options.lte == 'number') {
```
Comment (christian-bromann) [inline src/utils.ts:100]:
```suggestion
    if (typeof options.lte === 'number') {
```

**Review by christian-bromann — COMMENTED** [review]
Couple more comments

File: src/matchers/element/toHaveChildren.ts (hunk 8 above)
Comment (TuxedoFish) [reply src/matchers/element/toHaveChildren.ts:10]: Yes that makes sense, I'll push this change!

File: src/utils.ts (hunk 10 above)
Comment (TuxedoFish) [reply src/utils.ts:90]: pushing these up as well

File: src/utils.ts (hunk 9 above)
Comment (TuxedoFish) [reply src/utils.ts:86]: Okay, so should I just add in the === here or do you want me to refactor it a bit more?

**Review by christian-bromann — APPROVED** [review]
👍  great job!
